language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DATABASE=mysql DJANGO=1.11
  - DATABASE=postgresql DJANGO=1.11
  - DATABASE=sqlite DJANGO=1.11
  - DATABASE=mysql DJANGO=2.0
  - DATABASE=postgresql DJANGO=2.0
  - DATABASE=sqlite DJANGO=2.0
  - DATABASE=mysql DJANGO=2.1
  - DATABASE=postgresql DJANGO=2.1
  - DATABASE=sqlite DJANGO=2.1
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1
    - python: 3.4
      env: DJANGO=2.1
install:
  - pip install tox-travis coveralls
services:
  - mysql
  - postgresql
script:
  - tox
addons:
  postgresql: "9.5"
notifications:
  email: false
after_success:
  coveralls
